-- ============================================================================
-- ChandranganXSumit Navratrotsav - demo seed data
-- Run AFTER schema.sql
--
-- Super admin (full access):   admin      / Navratri@2026   (change after first login)
-- Limited admin (names + photos only): admin2 / Navratri@2026
-- ============================================================================

SET NAMES utf8mb4;

-- ----------------------------------------------------------------------------
-- Administrators
-- ----------------------------------------------------------------------------
INSERT INTO admins (username, password_hash, role, is_active, created_at, updated_at)
VALUES
  ('admin',  '$2y$12$zPzxI1S13x5yOMIrj26MI.NuAOsWCekOEgbGYn2RVFWj3Lbs513C2', 'super_admin', 1, NOW(), NOW()),
  ('admin2', '$2y$12$zPzxI1S13x5yOMIrj26MI.NuAOsWCekOEgbGYn2RVFWj3Lbs513C2', 'admin',       1, NOW(), NOW())
ON DUPLICATE KEY UPDATE username = username;

-- ----------------------------------------------------------------------------
-- Age groups
-- ----------------------------------------------------------------------------
INSERT INTO age_groups (id, name, description, is_active, sort_order, created_at, updated_at)
VALUES
  (1, 'Kids',            'Ages 5 - 10',        1, 1, NOW(), NOW()),
  (2, 'Teenagers',       'Ages 11 - 17',       1, 2, NOW(), NOW()),
  (3, 'Young Adults',    'Ages 18 - 25',       1, 3, NOW(), NOW()),
  (4, 'Adults',          'Ages 26 - 45',       1, 4, NOW(), NOW()),
  (5, 'Senior Citizens', 'Ages 60 and above',  1, 5, NOW(), NOW())
ON DUPLICATE KEY UPDATE name = VALUES(name);

-- ----------------------------------------------------------------------------
-- Event days - Navratri 2026: Day 1 = 11 Oct ... Day 9 = 19 Oct (editable in Settings)
-- ----------------------------------------------------------------------------
INSERT INTO event_days (id, label, event_date, is_active, created_at, updated_at)
VALUES
  (1, 'Day 1', '2026-10-11', 1, NOW(), NOW()),
  (2, 'Day 2', '2026-10-12', 1, NOW(), NOW()),
  (3, 'Day 3', '2026-10-13', 1, NOW(), NOW()),
  (4, 'Day 4', '2026-10-14', 1, NOW(), NOW()),
  (5, 'Day 5', '2026-10-15', 1, NOW(), NOW()),
  (6, 'Day 6', '2026-10-16', 1, NOW(), NOW()),
  (7, 'Day 7', '2026-10-17', 1, NOW(), NOW()),
  (8, 'Day 8', '2026-10-18', 1, NOW(), NOW()),
  (9, 'Day 9', '2026-10-19', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE label = VALUES(label), event_date = VALUES(event_date);

-- ----------------------------------------------------------------------------
-- Participants - exactly ONE winner per prize section (day x age group x prize),
--   so every section shows a single name: 1st = 1, 2nd = 1, 3rd = 1.
--   photo_path / photo_thumb_path are generated by database/generate_demo_photos.php
--   Note: "Rahul Sharma" appears in three different sections on purpose so the
--   duplicate-detection levels (exact / group / other) can be tested immediately.
-- ----------------------------------------------------------------------------
INSERT INTO participants
  (participant_code, name, normalized_name, day_id, age_group_id, prize_position,
   photo_path, photo_thumb_path, photo_width, photo_height, request_id, created_at, updated_at)
VALUES
  -- ===== Day 1 (11 Oct 2026): all 15 sections filled =====
  -- Kids (age group 1)
  ('NAV-0001', 'Rahul Sharma',      'rahul sharma',      1, 1, 1, 'participants/demo-01.webp', 'participants/demo-01_t.webp', 800, 800, NULL, '2026-10-11 10:15:00', '2026-10-11 10:15:00'),
  ('NAV-0002', 'Rahul Sharma',      'rahul sharma',      1, 1, 2, 'participants/demo-02.webp', 'participants/demo-02_t.webp', 800, 800, NULL, '2026-10-11 09:20:00', '2026-10-11 09:20:00'),
  ('NAV-0003', 'Diya Verma',        'diya verma',        1, 1, 3, 'participants/demo-03.webp', 'participants/demo-03_t.webp', 800, 800, NULL, '2026-10-11 16:05:00', '2026-10-11 16:05:00'),

  -- Teenagers (age group 2)
  ('NAV-0004', 'Ishita Reddy',      'ishita reddy',      1, 2, 1, 'participants/demo-04.webp', 'participants/demo-04_t.webp', 800, 800, NULL, '2026-10-11 11:10:00', '2026-10-11 11:10:00'),
  ('NAV-0005', 'Tanvi Deshmukh',    'tanvi deshmukh',    1, 2, 2, 'participants/demo-05.webp', 'participants/demo-05_t.webp', 800, 800, NULL, '2026-10-11 12:05:00', '2026-10-11 12:05:00'),
  ('NAV-0006', 'Meera Kulkarni',    'meera kulkarni',    1, 2, 3, 'participants/demo-06.webp', 'participants/demo-06_t.webp', 800, 800, NULL, '2026-10-11 10:55:00', '2026-10-11 10:55:00'),

  -- Young Adults (age group 3)
  ('NAV-0007', 'Neha Pillai',       'neha pillai',       1, 3, 1, 'participants/demo-07.webp', 'participants/demo-07_t.webp', 800, 800, NULL, '2026-10-11 18:10:00', '2026-10-11 18:10:00'),
  ('NAV-0008', 'Simran Kaur',       'simran kaur',       1, 3, 2, 'participants/demo-08.webp', 'participants/demo-08_t.webp', 800, 800, NULL, '2026-10-11 19:05:00', '2026-10-11 19:05:00'),
  ('NAV-0009', 'Ananya Bose',       'ananya bose',       1, 3, 3, 'participants/demo-09.webp', 'participants/demo-09_t.webp', 800, 800, NULL, '2026-10-11 10:00:00', '2026-10-11 10:00:00'),

  -- Adults (age group 4)
  ('NAV-0010', 'Sunita Agarwal',    'sunita agarwal',    1, 4, 1, 'participants/demo-10.webp', 'participants/demo-10_t.webp', 800, 800, NULL, '2026-10-11 17:15:00', '2026-10-11 17:15:00'),
  ('NAV-0011', 'Rahul Sharma',      'rahul sharma',      1, 4, 2, 'participants/demo-11.webp', 'participants/demo-11_t.webp', 800, 800, NULL, '2026-10-11 18:10:00', '2026-10-11 18:10:00'),
  ('NAV-0012', 'Pooja Mathe',       'pooja mathe',       1, 4, 3, 'participants/demo-12.webp', 'participants/demo-12_t.webp', 800, 800, NULL, '2026-10-11 12:20:00', '2026-10-11 12:20:00'),

  -- Senior Citizens (age group 5)
  ('NAV-0013', 'Ramesh Krishnan',   'ramesh krishnan',   1, 5, 1, 'participants/demo-13.webp', 'participants/demo-13_t.webp', 800, 800, NULL, '2026-10-11 16:10:00', '2026-10-11 16:10:00'),
  ('NAV-0014', 'Girish Pawar',      'girish pawar',      1, 5, 2, 'participants/demo-14.webp', 'participants/demo-14_t.webp', 800, 800, NULL, '2026-10-11 10:05:00', '2026-10-11 10:05:00'),
  ('NAV-0015', 'Kamla Ben Patel',   'kamla ben patel',   1, 5, 3, 'participants/demo-15.webp', 'participants/demo-15_t.webp', 800, 800, NULL, '2026-10-11 10:35:00', '2026-10-11 10:35:00'),

  -- ===== Day 2 (12 Oct 2026): a few winners so day switching is visible =====
  ('NAV-0016', 'Aarav Menon',       'aarav menon',       2, 1, 1, 'participants/demo-16.webp', 'participants/demo-16_t.webp', 800, 800, NULL, '2026-10-12 11:00:00', '2026-10-12 11:00:00'),
  ('NAV-0017', 'Rahul Sharma',      'rahul sharma',      2, 2, 3, 'participants/demo-17.webp', 'participants/demo-17_t.webp', 800, 800, NULL, '2026-10-12 12:30:00', '2026-10-12 12:30:00'),
  ('NAV-0018', 'Zoya Sheikh',       'zoya sheikh',       2, 4, 2, 'participants/demo-18.webp', 'participants/demo-18_t.webp', 800, 800, NULL, '2026-10-12 18:45:00', '2026-10-12 18:45:00')
ON DUPLICATE KEY UPDATE participant_code = VALUES(participant_code);

-- ----------------------------------------------------------------------------
--   Counters (participant codes continue from NAV-0018)
-- ----------------------------------------------------------------------------
INSERT INTO counters (name, value, updated_at)
VALUES ('participant', 18, NOW())
ON DUPLICATE KEY UPDATE value = GREATEST(value, VALUES(value));
--   so every section shows a single name: 1st = 1, 2nd = 1, 3rd = 1.
--   photo_path / photo_thumb_path are generated by database/generate_demo_photos.php
--   Note: "Rahul Sharma" appears in three different sections on purpose so the
--   duplicate-detection levels (exact / group / other) can be tested immediately.
-- ----------------------------------------------------------------------------
INSERT INTO participants
  (participant_code, name, normalized_name, age_group_id, prize_position,
   photo_path, photo_thumb_path, photo_width, photo_height, request_id, created_at, updated_at)
VALUES
  -- Kids (age group 1)
  ('NAV-0001', 'Rahul Sharma',      'rahul sharma',      1, 1, 'participants/demo-01.webp', 'participants/demo-01_t.webp', 800, 800, NULL, '2026-10-01 10:15:00', '2026-10-01 10:15:00'),
  ('NAV-0002', 'Rahul Sharma',      'rahul sharma',      1, 2, 'participants/demo-02.webp', 'participants/demo-02_t.webp', 800, 800, NULL, '2026-10-02 09:20:00', '2026-10-02 09:20:00'),
  ('NAV-0003', 'Diya Verma',        'diya verma',        1, 3, 'participants/demo-03.webp', 'participants/demo-03_t.webp', 800, 800, NULL, '2026-10-03 16:05:00', '2026-10-03 16:05:00'),

  -- Teenagers (age group 2)
  ('NAV-0004', 'Ishita Reddy',      'ishita reddy',      2, 1, 'participants/demo-04.webp', 'participants/demo-04_t.webp', 800, 800, NULL, '2026-10-02 11:10:00', '2026-10-02 11:10:00'),
  ('NAV-0005', 'Tanvi Deshmukh',    'tanvi deshmukh',    2, 2, 'participants/demo-05.webp', 'participants/demo-05_t.webp', 800, 800, NULL, '2026-10-02 12:05:00', '2026-10-02 12:05:00'),
  ('NAV-0006', 'Meera Kulkarni',    'meera kulkarni',    2, 3, 'participants/demo-06.webp', 'participants/demo-06_t.webp', 800, 800, NULL, '2026-10-03 10:55:00', '2026-10-03 10:55:00'),

  -- Young Adults (age group 3)
  ('NAV-0007', 'Neha Pillai',       'neha pillai',       3, 1, 'participants/demo-07.webp', 'participants/demo-07_t.webp', 800, 800, NULL, '2026-10-03 18:10:00', '2026-10-03 18:10:00'),
  ('NAV-0008', 'Simran Kaur',       'simran kaur',       3, 2, 'participants/demo-08.webp', 'participants/demo-08_t.webp', 800, 800, NULL, '2026-10-03 19:05:00', '2026-10-03 19:05:00'),
  ('NAV-0009', 'Ananya Bose',       'ananya bose',       3, 3, 'participants/demo-09.webp', 'participants/demo-09_t.webp', 800, 800, NULL, '2026-10-04 10:00:00', '2026-10-04 10:00:00'),

  -- Adults (age group 4)
  ('NAV-0010', 'Sunita Agarwal',    'sunita agarwal',    4, 1, 'participants/demo-10.webp', 'participants/demo-10_t.webp', 800, 800, NULL, '2026-10-04 17:15:00', '2026-10-04 17:15:00'),
  ('NAV-0011', 'Rahul Sharma',      'rahul sharma',      4, 2, 'participants/demo-11.webp', 'participants/demo-11_t.webp', 800, 800, NULL, '2026-10-04 18:10:00', '2026-10-04 18:10:00'),
  ('NAV-0012', 'Pooja Mathe',       'pooja mathe',       4, 3, 'participants/demo-12.webp', 'participants/demo-12_t.webp', 800, 800, NULL, '2026-10-06 12:20:00', '2026-10-06 12:20:00'),

  -- Senior Citizens (age group 5)
  ('NAV-0013', 'Ramesh Krishnan',   'ramesh krishnan',   5, 1, 'participants/demo-13.webp', 'participants/demo-13_t.webp', 800, 800, NULL, '2026-10-05 16:10:00', '2026-10-05 16:10:00'),
  ('NAV-0014', 'Girish Pawar',      'girish pawar',      5, 2, 'participants/demo-14.webp', 'participants/demo-14_t.webp', 800, 800, NULL, '2026-10-06 10:05:00', '2026-10-06 10:05:00'),
  ('NAV-0015', 'Kamla Ben Patel',   'kamla ben patel',   5, 3, 'participants/demo-15.webp', 'participants/demo-15_t.webp', 800, 800, NULL, '2026-10-06 10:35:00', '2026-10-06 10:35:00')
ON DUPLICATE KEY UPDATE participant_code = VALUES(participant_code);

-- ----------------------------------------------------------------------------
--   Counters (participant codes continue from NAV-0015)
-- ----------------------------------------------------------------------------
INSERT INTO counters (name, value, updated_at)
VALUES ('participant', 15, NOW())
ON DUPLICATE KEY UPDATE value = GREATEST(value, VALUES(value));
