-- ============================================================================
-- ChandranganXSumit Navratrotsav - demo seed data
-- Run AFTER schema.sql
--
-- Default admin login:  admin / Navratri@2026   (change it after first login)
-- ============================================================================

SET NAMES utf8mb4;

-- ----------------------------------------------------------------------------
-- Administrators
-- ----------------------------------------------------------------------------
INSERT INTO admins (username, password_hash, is_active, created_at, updated_at)
VALUES
  ('admin', '$2y$12$zPzxI1S13x5yOMIrj26MI.NuAOsWCekOEgbGYn2RVFWj3Lbs513C2', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE username = username;

-- ----------------------------------------------------------------------------
-- Age groups
-- ----------------------------------------------------------------------------
INSERT INTO age_groups (id, name, description, is_active, sort_order, created_at, updated_at)
VALUES
  (1, 'Kids',            'Ages 5 - 10',        1, 1, NOW(), NOW()),
  (2, 'Teenagers',       'Ages 11 - 17',       1, 2, NOW(), NOW()),
  (3, 'Young Adults',    'Ages 18 - 25',       1, 3, NOW(), NOW()),
  (4, 'Adults',          'Ages 26 - 45',       1, 4, NOW(), NOW()),
  (5, 'Senior Citizens', 'Ages 60 and above',  1, 5, NOW(), NOW())
ON DUPLICATE KEY UPDATE name = VALUES(name);

-- ----------------------------------------------------------------------------
-- Participants
--   photo_path / photo_thumb_path are generated by database/generate_demo_photos.php
--   Note: "Rahul Sharma" appears three times on purpose so the duplicate-detection
--   and registration-history features can be tested immediately.
-- ----------------------------------------------------------------------------
INSERT INTO participants
  (participant_code, name, normalized_name, age_group_id, prize_position,
   photo_path, photo_thumb_path, photo_width, photo_height, request_id, created_at, updated_at)
VALUES
  -- Kids (age group 1)
  ('NAV-0001', 'Rahul Sharma',      'rahul sharma',      1, 1, 'participants/demo-01.webp', 'participants/demo-01_t.webp', 800, 800, NULL, '2026-10-01 10:15:00', '2026-10-01 10:15:00'),
  ('NAV-0002', 'Priya Sharma',      'priya sharma',      1, 1, 'participants/demo-02.webp', 'participants/demo-02_t.webp', 800, 800, NULL, '2026-10-01 10:42:00', '2026-10-01 10:42:00'),
  ('NAV-0003', 'Aarav Mehta',       'aarav mehta',       1, 1, 'participants/demo-03.webp', 'participants/demo-03_t.webp', 800, 800, NULL, '2026-10-01 11:05:00', '2026-10-01 11:05:00'),
  ('NAV-0004', 'Anaya Joshi',       'anaya joshi',       1, 1, 'participants/demo-04.webp', 'participants/demo-04_t.webp', 800, 800, NULL, '2026-10-01 11:30:00', '2026-10-01 11:30:00'),
  ('NAV-0005', 'Rahul Sharma',      'rahul sharma',      1, 2, 'participants/demo-05.webp', 'participants/demo-05_t.webp', 800, 800, NULL, '2026-10-02 09:20:00', '2026-10-02 09:20:00'),
  ('NAV-0006', 'Kiara Singh',       'kiara singh',       1, 2, 'participants/demo-06.webp', 'participants/demo-06_t.webp', 800, 800, NULL, '2026-10-02 09:48:00', '2026-10-02 09:48:00'),
  ('NAV-0007', 'Reyansh Patel',     'reyansh patel',     1, 2, 'participants/demo-07.webp', 'participants/demo-07_t.webp', 800, 800, NULL, '2026-10-02 10:12:00', '2026-10-02 10:12:00'),
  ('NAV-0008', 'Diya Verma',        'diya verma',        1, 3, 'participants/demo-08.webp', 'participants/demo-08_t.webp', 800, 800, NULL, '2026-10-03 16:05:00', '2026-10-03 16:05:00'),
  ('NAV-0009', 'Arjun Nair',        'arjun nair',        1, 3, 'participants/demo-09.webp', 'participants/demo-09_t.webp', 800, 800, NULL, '2026-10-03 16:35:00', '2026-10-03 16:35:00'),
  ('NAV-0010', 'Sara Khan',         'sara khan',         1, 3, 'participants/demo-10.webp', 'participants/demo-10_t.webp', 800, 800, NULL, '2026-10-03 17:02:00', '2026-10-03 17:02:00'),

  -- Teenagers (age group 2)
  ('NAV-0011', 'Ishita Reddy',      'ishita reddy',      2, 1, 'participants/demo-11.webp', 'participants/demo-11_t.webp', 800, 800, NULL, '2026-10-02 11:10:00', '2026-10-02 11:10:00'),
  ('NAV-0012', 'Kabir Malhotra',    'kabir malhotra',    2, 1, 'participants/demo-12.webp', 'participants/demo-12_t.webp', 800, 800, NULL, '2026-10-02 11:40:00', '2026-10-02 11:40:00'),
  ('NAV-0013', 'Tanvi Deshmukh',    'tanvi deshmukh',    2, 2, 'participants/demo-13.webp', 'participants/demo-13_t.webp', 800, 800, NULL, '2026-10-02 12:05:00', '2026-10-02 12:05:00'),
  ('NAV-0014', 'Aditya Iyer',       'aditya iyer',       2, 2, 'participants/demo-14.webp', 'participants/demo-14_t.webp', 800, 800, NULL, '2026-10-03 10:25:00', '2026-10-03 10:25:00'),
  ('NAV-0015', 'Meera Kulkarni',    'meera kulkarni',    2, 3, 'participants/demo-15.webp', 'participants/demo-15_t.webp', 800, 800, NULL, '2026-10-03 10:55:00', '2026-10-03 10:55:00'),
  ('NAV-0016', 'Yash Bhosale',      'yash bhosale',      2, 3, 'participants/demo-16.webp', 'participants/demo-16_t.webp', 800, 800, NULL, '2026-10-03 11:20:00', '2026-10-03 11:20:00'),

  -- Young Adults (age group 3)
  ('NAV-0017', 'Neha Pillai',       'neha pillai',       3, 1, 'participants/demo-17.webp', 'participants/demo-17_t.webp', 800, 800, NULL, '2026-10-03 18:10:00', '2026-10-03 18:10:00'),
  ('NAV-0018', 'Rohan Chawla',      'rohan chawla',      3, 1, 'participants/demo-18.webp', 'participants/demo-18_t.webp', 800, 800, NULL, '2026-10-03 18:40:00', '2026-10-03 18:40:00'),
  ('NAV-0019', 'Simran Kaur',       'simran kaur',       3, 2, 'participants/demo-19.webp', 'participants/demo-19_t.webp', 800, 800, NULL, '2026-10-03 19:05:00', '2026-10-03 19:05:00'),
  ('NAV-0020', 'Devansh Rao',       'devansh rao',       3, 2, 'participants/demo-20.webp', 'participants/demo-20_t.webp', 800, 800, NULL, '2026-10-04 09:30:00', '2026-10-04 09:30:00'),
  ('NAV-0021', 'Ananya Bose',       'ananya bose',       3, 3, 'participants/demo-21.webp', 'participants/demo-21_t.webp', 800, 800, NULL, '2026-10-04 10:00:00', '2026-10-04 10:00:00'),
  ('NAV-0022', 'Karthik Subramanian','karthik subramanian', 3, 3, 'participants/demo-22.webp', 'participants/demo-22_t.webp', 800, 800, NULL, '2026-10-04 10:35:00', '2026-10-04 10:35:00'),

  -- Adults (age group 4)
  ('NAV-0023', 'Sunita Agarwal',    'sunita agarwal',    4, 1, 'participants/demo-23.webp', 'participants/demo-23_t.webp', 800, 800, NULL, '2026-10-04 17:15:00', '2026-10-04 17:15:00'),
  ('NAV-0024', 'Manish Trivedi',    'manish trivedi',    4, 1, 'participants/demo-24.webp', 'participants/demo-24_t.webp', 800, 800, NULL, '2026-10-04 17:45:00', '2026-10-04 17:45:00'),
  ('NAV-0025', 'Rahul Sharma',      'rahul sharma',      4, 2, 'participants/demo-25.webp', 'participants/demo-25_t.webp', 800, 800, NULL, '2026-10-04 18:10:00', '2026-10-04 18:10:00'),
  ('NAV-0026', 'Kavita Sinha',      'kavita sinha',      4, 2, 'participants/demo-26.webp', 'participants/demo-26_t.webp', 800, 800, NULL, '2026-10-05 11:05:00', '2026-10-05 11:05:00'),
  ('NAV-0027', 'Pooja Mathe',       'pooja mathe',       4, 3, 'participants/demo-27.webp', 'participants/demo-27_t.webp', 800, 800, NULL, '2026-10-06 12:20:00', '2026-10-06 12:20:00'),
  ('NAV-0028', 'Sandeep Kulkarni',  'sandeep kulkarni',  4, 3, 'participants/demo-28.webp', 'participants/demo-28_t.webp', 800, 800, NULL, '2026-10-06 12:50:00', '2026-10-06 12:50:00'),

  -- Senior Citizens (age group 5)
  ('NAV-0029', 'Ramesh Krishnan',   'ramesh krishnan',   5, 1, 'participants/demo-29.webp', 'participants/demo-29_t.webp', 800, 800, NULL, '2026-10-05 16:10:00', '2026-10-05 16:10:00'),
  ('NAV-0030', 'Shanti Devi',       'shanti devi',       5, 1, 'participants/demo-30.webp', 'participants/demo-30_t.webp', 800, 800, NULL, '2026-10-05 16:40:00', '2026-10-05 16:40:00'),
  ('NAV-0031', 'Girish Pawar',      'girish pawar',      5, 2, 'participants/demo-31.webp', 'participants/demo-31_t.webp', 800, 800, NULL, '2026-10-06 10:05:00', '2026-10-06 10:05:00'),
  ('NAV-0032', 'Kamla Ben Patel',   'kamla ben patel',   5, 3, 'participants/demo-32.webp', 'participants/demo-32_t.webp', 800, 800, NULL, '2026-10-06 10:35:00', '2026-10-06 10:35:00')
ON DUPLICATE KEY UPDATE participant_code = VALUES(participant_code);

-- ----------------------------------------------------------------------------
-- Counters (participant codes continue from NAV-0032)
-- ----------------------------------------------------------------------------
INSERT INTO counters (name, value, updated_at)
VALUES ('participant', 32, NOW())
ON DUPLICATE KEY UPDATE value = GREATEST(value, VALUES(value));
